### ISSUE TITLE
Custom event landing page

### ISSUE THREAD

**Issue by Earlo** [hackjunction/JunctionApp#158]
This is needed for Junction Connected

**Comment by khenriksson** [comment]
![image](https://user-images.githubusercontent.com/35761879/89871508-30f83c80-dbc0-11ea-9e23-b336ab0526a3.png)

Here's the plan for what needs to be custom for all events, pretty much everything that currently has a color. BUT would be good to take into account if we rework the whole page?

**Comment by Earlo** [comment]
Done with #387
