### ISSUE TITLE
https://projects.hackjunction.com/ should be closed

### ISSUE THREAD

**Issue by joonas-ai** [hackjunction/JunctionApp#276]
Includes only submissions from Junction 2018. The project gallery includes peoples emails which are visible for search engines. This site should be hidden as irrelevant.

**Comment by pholm** [comment]
I disagree with this. Showing old projects is good way to showcase something happens in our events. We can of course remove the emails, if you find that is good idea.

Also, let's post only issues regarding hackplatform here from now on

**Comment by joonas-ai** [comment]
Thought that it would be easier fix to hide the whole section, rather than using time to fix the email issue. I wonder if that page is even linked to anywhere for showcasing so doesn't make sense to host it.

My bad, searched through other repositories and hackplatform returned most results.

**Comment by Earlo** [comment]
This is completely different project from this one :D 

But yeah, it's kind of a mess, we should take the projects off from there and move them to current platform somehow.

**Comment by khenriksson** [comment]
What do we need to migrate it to the current platform? I suppose we need to tweak the data a little bit, but is this something that we have a plan for?
