### ISSUE TITLE
Select manually highlighted event

### ISSUE THREAD

**Issue by pholm** [hackjunction/JunctionApp#291]
Currently we cannot make Connected or other priority events highlighted. This is pretty bad for the participant flow. 

![image](https://user-images.githubusercontent.com/1903693/92230766-540ec700-eeb4-11ea-951e-7d2977299026.png)

**Comment by pholm** [comment]
@Earlo What is the status of this? At least hard coded version would be needed soon.

**Comment by Earlo** [comment]
this exists.
