### ISSUE TITLE
Going back to homepage

### ISSUE THREAD

**Issue by erintrk** [hackjunction/JunctionApp#317]
<img width="1680" alt="Screenshot 2020-09-18 at 15 57 31" src="https://user-images.githubusercontent.com/71508351/93600458-5733a800-f9c8-11ea-92a6-1769f8393901.png">

Can we just have the top of the page to look like this always, and have the junction text-logo a link to front page. it is such an extra step to go there from the menu, and a bit strange for this layout to dissapear only in two pages.

**Comment by Earlo** [comment]
Ah, yeah, this would make sense! I'll get this done asap.

Also, thanks for the other issues you've raised @erintrk  : )
