### ISSUE TITLE
BUG: Some upcoming events show "view projects" instead of apply now

### ISSUE THREAD

**Issue by pholm** [hackjunction/JunctionApp#403]
### What went wrong? 🤔

The event list on Junction App landing page.

### Expected Behavior

Only past events show the project gallery.

### Actual Behavior

One of the events shows gallery even though it's an upcoming event.

### Steps to Reproduce Issue

Can be seen on the live frontpage.

#### Operating System

macOS Big Sur

#### Browser

Chrome (stable)

### Screenshots

![image](https://user-images.githubusercontent.com/1903693/108503663-727b4a00-72bd-11eb-971d-4136fb05c7ff.png)

**Comment by khenriksson** [comment]
Can be closed as of #405
