### ISSUE TITLE
BUG: Front page crashes when creating new banner

### ISSUE THREAD

**Issue by pholm** [hackjunction/JunctionApp#437]
### What went wrong? 🤔

While creating new frontpage banners, the front page crashes. It seems it has something to do with adding the image: I created a banner with only text and it worked fine. 

### Expected Behavior

Creating new banner on admin panel, it would show up on the front page.

### Actual Behavior

The front page crashes. Console shows the following error.

![image](https://user-images.githubusercontent.com/1903693/119109011-7720dd00-ba29-11eb-8f64-ecbf8d205b73.png)

### Steps to Reproduce Issue

Create new banner with image (on dev environment).

#### Operating System

macOS Big Sur

#### Browser

Chrome

### Screenshots

![image](https://user-images.githubusercontent.com/1903693/119109700-0f1ec680-ba2a-11eb-8ff7-8518538bd4ae.png)

![image](https://user-images.githubusercontent.com/1903693/119109011-7720dd00-ba29-11eb-8f64-ecbf8d205b73.png)

**Comment by khenriksson** [comment]
Did you try adding a button to the image? Quickly looking at the code it does seem as if the event image does need a picture at the moment `
<EventImage ... buttons={picture.buttons} />
` in BannerCarousel/index.js. We should probably add `button && button.push &&` before startsWith in EventImage/index.js.

**Comment by pholm** [comment]
It's probably related to that, I think the UI related to button adding is a bit messy and therefore I forgot to "save button adding". 😄

**Comment by Jussii** [comment]
Thank you Kasper for fixing this issue!
