### ISSUE TITLE
Make left sidebar fixed instead of hide/show

### ISSUE THREAD

**Issue by pholm** [hackjunction/JunctionApp#441]
**Is your feature request related to a problem? Please describe.**
It's sometimes hard to find the view you are looking for in the Junction App, as the sidebar is hard to find. 

**Describe the solution you'd like**
Make sidebar always visible on desktop and tablet. 

**Describe alternatives you've considered**
No other ideas, but welcome for suggestions.

**Additional context**
Sidebar visible on manage event view. 
![image](https://user-images.githubusercontent.com/1903693/119837857-9e851780-bf0b-11eb-9cc6-22e5fcf7c24d.png)

**Comment by pholm** [comment]
@khenriksson thought you would be interested in this :D

**Comment by khenriksson** [comment]
I could take a look at some point, maybe this weekend!

**Comment by Earlo** [comment]
Most elegant way would to have this as a feature that can be enabled / disabled for the element via props.

**Comment by pholm** [comment]
Closed as it now defaults to being open. If we see in the future we want to force it open, let's reinvestigate the issue.
