### ISSUE TITLE
Project details cannot be opened in challenge-spesific view

### ISSUE THREAD

**Issue by pholm** [hackjunction/JunctionApp#88]
In Projects -> by challenge -> create partner link

The projects by challenge are rendered nicely, but when clicking "See more" from project card, nothing happens.

![image](https://user-images.githubusercontent.com/1903693/77121902-f50fdf80-6a44-11ea-916c-56f59c5b7667.png)
![image](https://user-images.githubusercontent.com/1903693/77121926-078a1900-6a45-11ea-87f6-4e349c2b2246.png)

**Comment by khenriksson** [comment]
Fixed in #338
